MODULE Rerun
USE COM
!CHARACTER (LEN=80) :: TEMP="Pheno_in.txt"
CHARACTER (LEN=80) :: COMMENT

CONTAINS
SUBROUTINE Rerun_Bilinear1()
REAL TBDn, TODn, TMDn, SPSPn, aEPSPn, MOPPn, PPSEn, SHCKDn
REAL TBDm, TODm, TMDm, SPSPm, aEPSPm, MOPPm, PPSEm, SHCKDm
REAL TBDs, TODs, TMDs, SPSPs, aEPSPs, MOPPs, PPSEs, SHCKDs
INTEGER ERROR

!-----Input min, max and step	
!for no PSP fill in PPSEn=0.0; PPSEm=0.0; PPSEs=0.05	
!and for clarity fill in SPSPn=0.0; SPSPm=0.1; SPSPs=1.0	
!	TBDn=-10.0; TBDm=8.0; TBDs=1.
!	TODn=16.0; TODm=36.1; TODs=1.
!	TMDn=100.0; TMDm=1000.1; TMDs=400.0
!	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
!	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
!	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
!	SHCKDn=-0.2; SHCKDm=1.0; SHCKDs=0.2
!-----End of input	
!with PSP, big step, no transplanting	
	TBDn=0.0; TBDm=20.0; TBDs=2.
	TODn=22.0; TODm=40.1; TODs=2.
	TMDn=42.0; TMDm=1000.1; TMDs=479.0
	SPSPn=5.0; SPSPm=50.1; SPSPs=5.0
	MOPPn=11.0; MOPPm=13.1; MOPPs=1.
	PPSEn=0.1; PPSEm=0.4; PPSEs=0.1
	SHCKDn=0.; SHCKDm=0.01; SHCKDs=0.4
!without PSP, small step, no transplanting	
!	TBDn=0.0; TBDm=20.0; TBDs=1.
!	TODn=22.0; TODm=40.1; TODs=1.
!	TMDn=42.0; TMDm=1000.1; TMDs=479.0
!	SPSPn=0.0; SPSPm=0.1; SPSPs=10.0
!	MOPPn=11.0; MOPPm=11.1; MOPPs=2.
!	PPSEn=0.0; PPSEm=0.01; PPSEs=0.4
!	SHCKDn=0.; SHCKDm=0.01; SHCKDs=0.4
!-----End of input	
! Short example run	
	TBDn=0.0; TBDm=16.1; TBDs=8.
	TODn=30.0; TODm=40.1; TODs=5.
	TMDn=100.0; TMDm=900.1; TMDs=400.0
	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
	SHCKDn=0.0; SHCKDm=0.81; SHCKDs=0.4
!ORYZA2000 default
!	TBDn=8.0; TBDm=8.1; TBDs=8.
!	TODn=30.0; TODm=30.1; TODs=5.
!	TMDn=42.0; TMDm=42.1; TMDs=400.0
!	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
!	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
!	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
!	SHCKDn=0.4; SHCKDm=0.41; SHCKDs=0.4


ALLOCATE (TBD_set( INT((TBDm-TBDn)/TBDs)+1 ))
ALLOCATE (TOD_set( INT((TODm-TODn)/TODs)+1 ))
ALLOCATE (TMD_set( INT((TMDm-TMDn)/TMDs)+1 ))
ALLOCATE (SPSP_set( INT((SPSPm-SPSPn)/SPSPs)+1 ))
ALLOCATE (MOPP_set( INT((MOPPm-MOPPn)/MOPPs)+1 ))
ALLOCATE (PPSE_set( INT((PPSEm-PPSEn)/PPSEs)+1 ))	
ALLOCATE (SHCKD_set( INT((SHCKDm-SHCKDn)/SHCKDs)+1 ))

	DO I=1, INT((TBDm-TBDn)/TBDs)+1, 1
		TBD_set(I)= TBDn+TBDs*(I-1)
	END DO
	DO I=1, INT((TODm-TODn)/TODs)+1, 1
		TOD_set(I)= TODn+TODs*(I-1)
	END DO
	DO I=1, INT((TMDm-TMDn)/TMDs)+1, 1
		TMD_set(I)= TMDn+TMDs*(I-1)
	END DO
	DO I=1, INT((SPSPm-SPSPn)/SPSPs)+1, 1
		SPSP_set(I)= SPSPn+SPSPs*(I-1)
	END DO
	DO I=1, INT((MOPPm-MOPPn)/MOPPs)+1, 1
		MOPP_set(I)= MOPPn+MOPPs*(I-1)
	END DO
	DO I=1, INT((PPSEm-PPSEn)/PPSEs)+1, 1
		PPSE_set(I)= PPSEn+PPSEs*(I-1)
	END DO
	DO I=1, INT((SHCKDm-SHCKDn)/SHCKDs)+1, 1
		SHCKD_set(I)= SHCKDn+SHCKDs*(I-1)
	END DO

!OPEN (13, FILE=TEMP)
OPEN (13, FILE=Pheno_in)

EXP_NUM=0
DO WHILE (.TRUE.)
100	  READ (13,"(A80)",IOSTAT=ERROR) comment        

	  IF(ERROR/=0) GOTO 102

	  IF (comment(1:1)=="*") THEN 
	  	GOTO 100
	  ELSE				
		BACKSPACE (13)
        READ(13,*) 	
		EXP_NUM=EXP_NUM+1			
		GOTO 101
	  END IF
101 CONTINUE
END DO
102 CONTINUE
CLOSE (13)

OUTPUT_NUM=EXP_NUM*SIZE(TBD_set)*SIZE(TOD_set)*SIZE(TMD_set)*SIZE(SPSP_set)*SIZE(MOPP_set)*SIZE(PPSE_set)*SIZE(SHCKD_set)

RETURN
END SUBROUTINE


SUBROUTINE Rerun_Bilinear2()

REAL TBDn, TODn, TMDn, SPSPn, aEPSPn, MOPPn, PPSEn, TODNGHTn, SHCKDn
REAL TBDm, TODm, TMDm, SPSPm, aEPSPm, MOPPm, PPSEm, TODNGHTm, SHCKDm
REAL TBDs, TODs, TMDs, SPSPs, aEPSPs, MOPPs, PPSEs, TODNGHTs, SHCKDs
INTEGER ERROR

!-----Input min, max and step
!for no PSP fill in PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
!and for clarity fill in SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	TBDn=8.0; TBDm=16.0; TBDs=1.
	TODn=26.0; TODm=36.1; TODs=1.
	TODNGHTn=26.0; TODNGHTm=36.1; TODNGHTs=1.
	TMDn=42.0; TMDm=942.1; TMDs=900.0
	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
	SHCKDn=0.0; SHCKDm=0.4; SHCKDs=0.4
!-----End of input
! Short example run
	TBDn=0.0; TBDm=16.1; TBDs=8.
	TODn=30.0; TODm=30.1; TODs=1.
	TODNGHTn=28.0; TODNGHTm=28.1; TODNGHTs=1.
	TMDn=100.0; TMDm=900.1; TMDs=400.0
	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
	SHCKDn=0.0; SHCKDm=0.81; SHCKDs=0.4

ALLOCATE (TBD_set( INT((TBDm-TBDn)/TBDs)+1 ))
ALLOCATE (TOD_set( INT((TODm-TODn)/TODs)+1 ))
ALLOCATE (TODNGHT_set( INT((TODNGHTm-TODNGHTn)/TODNGHTs)+1 ))
ALLOCATE (TMD_set( INT((TMDm-TMDn)/TMDs)+1 ))
ALLOCATE (SPSP_set( INT((SPSPm-SPSPn)/SPSPs)+1 ))
ALLOCATE (MOPP_set( INT((MOPPm-MOPPn)/MOPPs)+1 ))
ALLOCATE (PPSE_set( INT((PPSEm-PPSEn)/PPSEs)+1 ))
ALLOCATE (SHCKD_set( INT((SHCKDm-SHCKDn)/SHCKDs)+1 ))
	
	DO I=1, INT((TBDm-TBDn)/TBDs)+1, 1
		TBD_set(I)= TBDn+TBDs*(I-1)
	END DO
	DO I=1, INT((TODm-TODn)/TODs)+1, 1
		TOD_set(I)= TODn+TODs*(I-1)
	END DO
	DO I=1, INT((TODNGHTm-TODNGHTn)/TODNGHTs)+1, 1
		TODNGHT_set(I)= TODNGHTn+TODNGHTs*(I-1)
	END DO
	DO I=1, INT((TMDm-TMDn)/TMDs)+1, 1
		TMD_set(I)= TMDn+TMDs*(I-1)
	END DO
	DO I=1, INT((SPSPm-SPSPn)/SPSPs)+1, 1
		SPSP_set(I)= SPSPn+SPSPs*(I-1)
	END DO
	DO I=1, INT((MOPPm-MOPPn)/MOPPs)+1, 1
		MOPP_set(I)= MOPPn+MOPPs*(I-1)
	END DO
	DO I=1, INT((PPSEm-PPSEn)/PPSEs)+1, 1
		PPSE_set(I)= PPSEn+PPSEs*(I-1)
	END DO
	DO I=1, INT((SHCKDm-SHCKDn)/SHCKDs)+1, 1
		SHCKD_set(I)= SHCKDn+SHCKDs*(I-1)
	END DO

!OPEN (13, FILE=TEMP)
OPEN (13, FILE=Pheno_in)
EXP_NUM=0
DO WHILE (.TRUE.)
103	  READ (13,"(A80)",IOSTAT=ERROR) comment        

	  IF(ERROR/=0) GOTO 105

	  IF (comment(1:1)=="*") THEN 
	  	GOTO 103
	  ELSE				
		BACKSPACE (13)
        READ(13,*) 	
		EXP_NUM=EXP_NUM+1			
		GOTO 104
	  END IF
104 CONTINUE
END DO
105 CONTINUE
CLOSE (13)

OUTPUT_NUM=EXP_NUM*SIZE(TBD_set)*SIZE(TOD_set)*SIZE(TODNGHT_set)*SIZE(TMD_set)*SIZE(SPSP_set) &
            *SIZE(MOPP_set)*SIZE(PPSE_set)*SIZE(SHCKD_set)

RETURN
END SUBROUTINE

SUBROUTINE Rerun_Bilinear3()

REAL TBDn, TODn, TMDn, SPSPn, aEPSPn, MOPPn, PPSEn, SHCKDn, TM_CORRn
REAL TBDm, TODm, TMDm, SPSPm, aEPSPm, MOPPm, PPSEm, SHCKDm, TM_CORRm
REAL TBDs, TODs, TMDs, SPSPs, aEPSPs, MOPPs, PPSEs, SHCKDs, TM_CORRs
INTEGER ERROR

!-----Input min, max and step
!for no PSP fill in PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
!and for clarity fill in SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	TBDn=8.0; TBDm=20.0; TBDs=2.
	TODn=26.0; TODm=36.1; TODs=1.
	TMDn=42.0; TMDm=942.1; TMDs=900.0
	TM_CORRn=-10.0; TM_CORRm=0.0; TM_CORRs=2.
	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
	SHCKDn=0.0; SHCKDm=0.4; SHCKDs=0.4
!-----End of input
! Short example run
	TBDn=0.0; TBDm=16.1; TBDs=8.
	TODn=30.0; TODm=30.1; TODs=1.
	TM_CORRn=-10.0; TM_CORRm=0.0; TM_CORRs=2.
	TMDn=100.0; TMDm=900.1; TMDs=400.0
	SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
	MOPPn=10.0; MOPPm=10.1; MOPPs=1.
	PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
	SHCKDn=0.0; SHCKDm=0.81; SHCKDs=0.4

ALLOCATE (TBD_set( INT((TBDm-TBDn)/TBDs)+1 ))
ALLOCATE (TOD_set( INT((TODm-TODn)/TODs)+1 ))
ALLOCATE (TMD_set( INT((TMDm-TMDn)/TMDs)+1 ))
ALLOCATE (SPSP_set( INT((SPSPm-SPSPn)/SPSPs)+1 ))
ALLOCATE (MOPP_set( INT((MOPPm-MOPPn)/MOPPs)+1 ))
ALLOCATE (PPSE_set( INT((PPSEm-PPSEn)/PPSEs)+1 ))	
ALLOCATE (SHCKD_set( INT((SHCKDm-SHCKDn)/SHCKDs)+1 ))
ALLOCATE (TM_CORR_set (INT((TM_CORRm-TM_CORRn)/TM_CORRs)+1) )

	DO I=1, INT((TBDm-TBDn)/TBDs)+1, 1
		TBD_set(I)= TBDn+TBDs*(I-1)
	END DO
	DO I=1, INT((TODm-TODn)/TODs)+1, 1
		TOD_set(I)= TODn+TODs*(I-1)
	END DO
	DO I=1, INT((TMDm-TMDn)/TMDs)+1, 1
		TMD_set(I)= TMDn+TMDs*(I-1)
	END DO
	DO I=1, INT((SPSPm-SPSPn)/SPSPs)+1, 1
		SPSP_set(I)= SPSPn+SPSPs*(I-1)
	END DO
	DO I=1, INT((MOPPm-MOPPn)/MOPPs)+1, 1
		MOPP_set(I)= MOPPn+MOPPs*(I-1)
	END DO
	DO I=1, INT((PPSEm-PPSEn)/PPSEs)+1, 1
		PPSE_set(I)= PPSEn+PPSEs*(I-1)
	END DO
	DO I=1, INT((SHCKDm-SHCKDn)/SHCKDs)+1, 1
		SHCKD_set(I)= SHCKDn+SHCKDs*(I-1)
	END DO

	DO I=1, INT((TM_CORRm-TM_CORRn)/TM_CORRs)+1, 1
		TM_CORR_set(I)= TM_CORRn+TM_CORRs*(I-1)
	END DO

!OPEN (13, FILE=TEMP)
OPEN (13, FILE=Pheno_in)

EXP_NUM=0
DO WHILE (.TRUE.)
100	  READ (13,"(A80)",IOSTAT=ERROR) comment        

	  IF(ERROR/=0) GOTO 102

	  IF (comment(1:1)=="*") THEN 
	  	GOTO 100
	  ELSE				
		BACKSPACE (13)
        READ(13,*) 	
		EXP_NUM=EXP_NUM+1			
		GOTO 101
	  END IF
101 CONTINUE
END DO
102 CONTINUE
CLOSE (13)

OUTPUT_NUM=EXP_NUM*SIZE(TBD_set)*SIZE(TOD_set)*SIZE(TMD_set)*SIZE(SPSP_set)*SIZE(MOPP_set)*SIZE(PPSE_set) &
*SIZE(SHCKD_set)*SIZE(TM_CORR_set)


RETURN
END SUBROUTINE




SUBROUTINE Rerun_Beta()

REAL TBDn, TODn, TMDn, SPSPn, aEPSPn, MOPPn, PPSEn, TODNGHTn, TSENn, TSENNGHTn, TSENPSPn, TSENPSPNGHTn, SHCKDn
REAL TBDm, TODm, TMDm, SPSPm, aEPSPm, MOPPm, PPSEm, TODNGHTm, TSENm, TSENNGHTm, TSENPSPm, TSENPSPNGHTm, SHCKDm
REAL TBDs, TODs, TMDs, SPSPs, aEPSPs, MOPPs, PPSEs, TODNGHTs, TSENs, TSENNGHTs, TSENPSPs, TSENPSPNGHTs, SHCKDs
INTEGER ERROR

!-----Input min, max and step
!for no PSP fill in PPSEn=0.0; PPSEm=0.0; PPSEs=0.05
!and for clarity fill in SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
TBDn=8.0; TBDm=8.1; TBDs=1.0
TMDn=42.0; TMDm=42.1; TMDs=1.0
TODn=26.; TODm=36.1; TODs=2.0
TODNGHTn=26.0; TODNGHTm=36.0; TODNGHTs=2.0
TSENn=1. ; TSENm=7.1 ; TSENs=1.
TSENNGHTn= 1.; TSENNGHTm= 7.1; TSENNGHTs= 1.
TSENPSPn= 1. ; TSENPSPm= 7.1; TSENPSPs=1.
TSENPSPNGHTn= 1.; TSENPSPNGHTm= 7.1; TSENPSPNGHTs=1.
SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
MOPPn=10.0; MOPPm=10.1; MOPPs=1.0
PPSEn=0.; PPSEm=0.; PPSEs=4.0
SHCKDn=0.0; SHCKDm=0.0; SHCKDs=0.4
! Short example run
! but re-estimate SPSP, EPSP, CPTUFL, CPTUFLM
TBDn=8.0; TBDm=8.1; TBDs=1.0
TMDn=42.0; TMDm=42.1; TMDs=1.0
TODn=26.; TODm=36.1; TODs=4.0
TODNGHTn=26.0; TODNGHTm=36.0; TODNGHTs=4.0
TSENn=1. ; TSENm=7.1 ; TSENs=6.
TSENNGHTn= 1.; TSENNGHTm= 7.1; TSENNGHTs= 6.
TSENPSPn= 1. ; TSENPSPm= 7.1; TSENPSPs=6.
TSENPSPNGHTn= 1.; TSENPSPNGHTm= 7.1; TSENPSPNGHTs=6.
SPSPn=0.0; SPSPm=0.1; SPSPs=1.0
MOPPn=10.0; MOPPm=10.1; MOPPs=1.0
PPSEn=0.; PPSEm=0.; PPSEs=4.0
SHCKDn=0.0; SHCKDm=0.0; SHCKDs=0.4
!-----End of input

ALLOCATE (TBD_set( INT((TBDm-TBDn)/TBDs)+1 ))
ALLOCATE (TOD_set( INT((TODm-TODn)/TODs)+1 ))
ALLOCATE (TODNGHT_set( INT((TODNGHTm-TODNGHTn)/TODNGHTs)+1 ))
ALLOCATE (TMD_set( INT((TMDm-TMDn)/TMDs)+1 ))
ALLOCATE (SPSP_set( INT((SPSPm-SPSPn)/SPSPs)+1 ))
ALLOCATE (MOPP_set( INT((MOPPm-MOPPn)/MOPPs)+1 ))
ALLOCATE (PPSE_set( INT((PPSEm-PPSEn)/PPSEs)+1 ))
ALLOCATE (TSEN_set( INT((TSENm-TSENn)/TSENs)+1 ))
ALLOCATE (TSENNGHT_set( INT((TSENNGHTm-TSENNGHTn)/TSENNGHTs)+1 ))
ALLOCATE (TSENPSP_set( INT((TSENPSPm-TSENPSPn)/TSENPSPs)+1 ))
ALLOCATE (TSENPSPNGHT_set( INT((TSENPSPNGHTm-TSENPSPNGHTn)/TSENPSPNGHTs)+1 ))
ALLOCATE (SHCKD_set( INT((SHCKDm-SHCKDn)/SHCKDs)+1 ))
	
	DO I=1, INT((TBDm-TBDn)/TBDs)+1, 1
		TBD_set(I)= TBDn+TBDs*(I-1)
	END DO
	DO I=1, INT((TODm-TODn)/TODs)+1, 1
		TOD_set(I)= TODn+TODs*(I-1)
	END DO
	DO I=1, INT((TODNGHTm-TODNGHTn)/TODNGHTs)+1, 1
		TODNGHT_set(I)= TODNGHTn+TODNGHTs*(I-1)
	END DO
	DO I=1, INT((TMDm-TMDn)/TMDs)+1, 1
		TMD_set(I)= TMDn+TMDs*(I-1)
	END DO
	DO I=1, INT((SPSPm-SPSPn)/SPSPs)+1, 1
		SPSP_set(I)= SPSPn+SPSPs*(I-1)
	END DO
	DO I=1, INT((MOPPm-MOPPn)/MOPPs)+1, 1
		MOPP_set(I)= MOPPn+MOPPs*(I-1)
	END DO
	DO I=1, INT((PPSEm-PPSEn)/PPSEs)+1, 1
		PPSE_set(I)= PPSEn+PPSEs*(I-1)
	END DO
	DO I=1, INT((TSENm-TSENn)/TSENs)+1, 1
		TSEN_set(I)= TSENn+TSENs*(I-1)
	END DO
	DO I=1, INT((TSENNGHTm-TSENNGHTn)/TSENNGHTs)+1, 1
		TSENNGHT_set(I)= TSENNGHTn+TSENNGHTs*(I-1)
	END DO
	DO I=1, INT((TSENPSPm-TSENPSPn)/TSENPSPs)+1, 1
		TSENPSP_set(I)= TSENPSPn+TSENPSPs*(I-1)
	END DO
	DO I=1, INT((TSENPSPNGHTm-TSENPSPNGHTn)/TSENPSPNGHTs)+1, 1
		TSENPSPNGHT_set(I)= TSENPSPNGHTn+TSENPSPNGHTs*(I-1)
	END DO
	DO I=1, INT((SHCKDm-SHCKDn)/SHCKDs)+1, 1
		SHCKD_set(I)= SHCKDn+SHCKDs*(I-1)
	END DO

!OPEN (13, FILE=TEMP)
OPEN (13, FILE=Pheno_in)

EXP_NUM=0
DO WHILE (.TRUE.)
106	  READ (13,"(A80)",IOSTAT=ERROR) comment        

	  IF(ERROR/=0) GOTO 108

	  IF (comment(1:1)=="*") THEN 
	  	GOTO 106
	  ELSE				
		BACKSPACE (13)
        READ(13,*) 	
		EXP_NUM=EXP_NUM+1			
		GOTO 107
	  END IF
107 CONTINUE
END DO
108 CONTINUE
CLOSE (13)

! in case of PSP run 
OUTPUT_NUM=EXP_NUM*SIZE(TBD_set)*SIZE(TOD_set)*SIZE(TODNGHT_set)*SIZE(TMD_set)*SIZE(SPSP_set)*SIZE(MOPP_set)*SIZE(PPSE_set) &
*SIZE(TSEN_set)*SIZE(TSENNGHT_set)*SIZE(TSENPSP_set)*SIZE(TSENPSPNGHT_set)*SIZE(SHCKD_set)
! in case of NOPSP run 
!OUTPUT_NUM=EXP_NUM*SIZE(TBD_set)*SIZE(TOD_set)*SIZE(TODNGHT_set)*SIZE(TMD_set)*SIZE(TSEN_set)*SIZE(TSENNGHT_set)*SIZE(SHCKD_set)

!write (*,*) output_num, exp_num
!STOP
RETURN
END SUBROUTINE
END MODULE