MODULE STATISTICS
USE COM
!INTEGER SET
CHARACTER (LEN=80) output_sta
CHARACTER (LEN=200) :: TheEnd
CHARACTER (LEN=80) :: TEMP
!CHARACTER (LEN=80) :: pheno="Pheno_in.txt"
REAL, ALLOCATABLE :: OUTPUT1(:,:), OUTPUT2(:,:)

CONTAINS
SUBROUTINE Read_Output_bilinear1()
REAL DATASET_EPI_TMEFL(2, EXP_NUM),DATASET_PIFL_TMEFL(2,EXP_NUM),DATASET_FLM_TMFLM(2,EXP_NUM),DATASET_EM_TMEM(2,EXP_NUM)
REAL DATASET_EFL_TMEFL(2, EXP_NUM)
REAL DATASET_CPTUTRA(EXP_NUM),DATASET_EFLERROR(EXP_NUM),DATASET_FLMERROR(EXP_NUM)

REAL day_normal (EXP_NUM), experiment (11,EXP_NUM)
REAL SLOPE, R, RMSE, AVERAGE
!REAL, ALLOCATABLE :: OUTPUT1(:,:)
CHARACTER (LEN=80) :: INPUT="output_Bilinear1.txt"


!SET = OUTPUT_NUM/EXP_NUM
ALLOCATE (OUTPUT1(42,EXP_NUM))
ALLOCATE (OUTPUT2(28,SET))

!------calcuating normalized emergence dates
!OPEN (16, FILE=pheno)
!DO I=1,EXP_NUM
!		read (16, *) (experiment(J,I) ,j=1,11)
!END DO
!CLOSE (16)
!------The End

!CALL normalize (experiment,11,EXP_NUM, day_normal)

OPEN (15, FILE=INPUT)
READ (15,*) TEMP
DO I=1,SET,1
	DO J=1,EXP_NUM,1
!		READ (15, "(F10.0,',',16(F6.2,','),24(F5.0,','),F6.2)") OUTPUT1(1,J), OUTPUT1(2,J), OUTPUT1(3,J), OUTPUT1(4,J), &
		READ (15, 103) OUTPUT1(1,J), OUTPUT1(2,J), OUTPUT1(3,J), OUTPUT1(4,J), &
		OUTPUT1(5,J), OUTPUT1(6,J), OUTPUT1(7,J), OUTPUT1(8,J), OUTPUT1(9,J), OUTPUT1(10,J), OUTPUT1(11,J), OUTPUT1(12,J), &
		OUTPUT1(13,J), OUTPUT1(14,J), OUTPUT1(15,J), OUTPUT1(16,J), OUTPUT1(17,J), OUTPUT1(18,J),OUTPUT1(19,J), OUTPUT1(20,J), &
		OUTPUT1(21,J), OUTPUT1(22,J), OUTPUT1(23,J), OUTPUT1(24,J), OUTPUT1(25,J), OUTPUT1(26,J), OUTPUT1(27,J), OUTPUT1(28,J), &
		OUTPUT1(29,J), OUTPUT1(30,J), OUTPUT1(31,J), OUTPUT1(32,J), OUTPUT1(33,J), OUTPUT1(34,J), OUTPUT1(35,J), OUTPUT1(36,J), &
		OUTPUT1(37,J), OUTPUT1(38,J), OUTPUT1(39,J), OUTPUT1(40,J), OUTPUT1(41,J), OUTPUT1(42,J)
!        103 FORMAT (F10.0,",",16(F8.2,","),24(F5.0,","),F8.2)
        103 FORMAT (F10.0,1X,16(F8.2,1X),24(F5.0,1X),F8.2)
		OUTPUT2(1,I)=OUTPUT1(1,J)
		OUTPUT2(2,I)=OUTPUT1(2,J)
		OUTPUT2(3,I)=OUTPUT1(3,J)
		OUTPUT2(4,I)=OUTPUT1(4,J)
		OUTPUT2(5,I)=OUTPUT1(5,J)
		OUTPUT2(6,I)=OUTPUT1(6,J)
		OUTPUT2(7,I)=OUTPUT1(7,J)
		OUTPUT2(8,I)=OUTPUT1(8,J)
		OUTPUT2(9,I)=OUTPUT1(9,J)
		OUTPUT2(10,I)=OUTPUT1(10,J)
		OUTPUT2(11,I)=OUTPUT1(11,J)

!For regression IEPI-IEPISIM = a+b*TMEFL (note strictly it would be nicer to regress against TMEPI)
		DATASET_EPI_TMEFL(1,J) = OUTPUT1(15,J)					! TMEFL in column 15 of output_Bilinear1.txt
		DATASET_EPI_TMEFL(2,J) = OUTPUT1(34,J)-OUTPUT1(35,J)	! IEPI - IEPISIM, columns 34 & 35 of output_Bilinear1.txt
!For regression IPIFL-IPIFLSIM = a+b*TMEFL (note strictly it would be nicer to regress against TMPIFL)
		DATASET_PIFL_TMEFL(1,J) = OUTPUT1(15,J)					! TMEFL in column 15 of output_Bilinear1.txt
		DATASET_PIFL_TMEFL(2,J) = OUTPUT1(36,J)-OUTPUT1(37,J)	! IPIFL - IPIFLSIM, columns 36 & 37 of output_Bilinear1.txt
!For regression IEFL-IEFLSIM = a+b*TMEFL
		DATASET_EFL_TMEFL(1,J) = OUTPUT1(15,J)					! TMEFL in column 15 of output_Bilinear1.txt
		DATASET_EFL_TMEFL(2,J) = OUTPUT1(38,J) - OUTPUT1(39,J)	! IEFL-IEFLSIM in column 38 & 39 of output_Bilinear1.txt
		DATASET_EFLERROR(J) = OUTPUT1(38,J) - OUTPUT1(39,J)
!For regression IFLM-IFLMSIM = a+b*TMFLM
		DATASET_FLM_TMFLM(1,J) = OUTPUT1(16,J)					! TMFLM in column 16 of output_Bilinear1.txt
		DATASET_FLM_TMFLM(2,J) = OUTPUT1(40,J) - OUTPUT1(41,J)	! IFLM-IFLMSIM in column 40 & 41 of output_Bilinear1.txt
		DATASET_FLMERROR(J) = OUTPUT1(40,J) - OUTPUT1(41,J) 
!For regression IEM-IEMSIM = a+b*TMEM
		DATASET_EM_TMEM(1,J) = OUTPUT1(17,J)					! TMEM in column 17 of output_Bilinear1.txt
		DATASET_EM_TMEM(2,J) = (OUTPUT1(38,J)+OUTPUT1(40,J))-(OUTPUT1(39,J)+OUTPUT1(41,J))	!(IEFL+IFLM)-(IEFLSIM+IFLMSIM)
!Average CPTU at which transplanting
		DATASET_CPTUTRA(J) = OUTPUT1(42,J) 
	END DO 
!Do the regressions
	CALL SlopeCVR(DATASET_EPI_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (12,I) =SLOPE; OUTPUT2 (13,I) =RMSE
	CALL SlopeCVR(DATASET_PIFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (14,I) =SLOPE; OUTPUT2 (15,I) =RMSE
	CALL SlopeCVR(DATASET_EFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (16,I) =SLOPE; OUTPUT2 (17,I) =RMSE
	CALL AVE(DATASET_EFLERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (18,I) = AVERAGE
	CALL SlopeCVR(DATASET_FLM_TMFLM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (19,I) =SLOPE; OUTPUT2 (20,I) =RMSE
	CALL AVE(DATASET_EFLERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (21,I) = AVERAGE
	CALL SlopeCVR(DATASET_EM_TMEM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (22,I) =SLOPE; OUTPUT2 (23,I) =RMSE
	CALL AVE(DATASET_CPTUTRA, EXP_NUM, AVERAGE)
	OUTPUT2 (24,I) = AVERAGE
!Calculate development rates, rescale such that:
!0.0-0.4 = Basic Vegetative Phase
!0.4-0.65 = Photoperiod Sensitive Phase (ending at Panicle Initiation PI)
!0.65-1.0 = Post Photoperiod Sensitive Phase
!1.0-2.0 = Reproductive Phase
!	DVRJ = 0.4/SPSP
!	DVRI = (0.65-0.4)/(EPSP-SPSP)
!	DVRP = (1.-0.65)/(CPTUFL-EPSP)
!	DVRR = (2.-1.)/CPTUFLM
	IF (OUTPUT1(24,1).EQ.0..OR.OUTPUT1(5,1).EQ.0.) THEN ! IF NOT PHOTOPERIOD SENSITIVE TREAT BVP+PSP as one phase with same DVR
		DVRJ = 0.65/OUTPUT1(6,1)
		DVRI = DVRJ
	ELSE
		DVRJ = 0.4/OUTPUT1(5,1)
		DVRI = (0.65-0.4)/(OUTPUT1(6,1)-OUTPUT1(5,1))
	ENDIF
	DVRP = (1.-0.65)/(OUTPUT1(10,1)-OUTPUT1(6,1))
	DVRR = (2.-1.)/OUTPUT1(11,1)
	OUTPUT2(25,I) = DVRJ
	OUTPUT2(26,I) = DVRI
	OUTPUT2(27,I) = DVRP
	OUTPUT2(28,I) = DVRR
END DO
CLOSE (15)
output_sta="SlopeCV_bilinear1.txt"
OPEN (14, FILE=output_sta)
WRITE (14,"(A250)") "*SET,TBD,TOD,TMD,SPSP,EPSP,MOPP,PPSE,SHCKD,CPTUFL,CPTUFLM,SLOPEEPI_TMEFL,RMSE_EPI,SLOPEPIFL_TMEFL, &
RMSE_PIFL,SLOPEEFL_TMEFL,RMSE_EFL,AVE(IEFL-IEFLSIM),SLOPEFLM_TMFLM,RMSE_FLM,AVE(IFLM-IFLMSIM),SLOPEEM_TMEM,RMSE_EM, &
AVE(CPTUTRA),DVRJ,DVRI,DVRP,DVRR"
DO I=1,SET
	WRITE (14,100) (OUTPUT2(J,I), J=1,28)
	100 FORMAT (F10.0,",",10(F8.2,","), 12(F9.3, ","),F8.2,",",4(F10.7, ","))
END DO
CLOSE (14)
IF (OUTPUT1(24,1).EQ.0.) THEN
	WRITE(*,*)"You have not simulated PI. Take a good guess (e.g. 0.73*CPTUFL or IDOYFL - 20 to -30 days) and fill in the &
	Pheno_in.txt file"
ENDIF



DEALLOCATE (OUTPUT1)
DEALLOCATE (OUTPUT2)

RETURN
END SUBROUTINE


SUBROUTINE Read_Output_bilinear2()
REAL DATASET_EPI_TMEFL(2, EXP_NUM),DATASET_PIFL_TMEFL(2,EXP_NUM),DATASET_FLM_TMFLM(2,EXP_NUM),DATASET_EM_TMEM(2,EXP_NUM)
REAL DATASET_EFL_TMEFL(2, EXP_NUM)
REAL DATASET_CPTUTRA(EXP_NUM),DATASET_EFLERROR(EXP_NUM),DATASET_FLMERROR(EXP_NUM)

REAL day_normal (EXP_NUM), experiment (11,EXP_NUM)
REAL SLOPE, R, RMSE, AVERAGE
!REAL, ALLOCATABLE :: OUTPUT1(:,:)
CHARACTER (LEN=80) :: INPUT="output_Bilinear2.txt"

!SET = OUTPUT_NUM/EXP_NUM
ALLOCATE (OUTPUT1(43,EXP_NUM))
ALLOCATE (OUTPUT2(29,SET))

!------calcuating normalized emergence dates
!OPEN (16, FILE=pheno)
!DO I=1,EXP_NUM
!		read (16, *) (experiment(J,I) ,j=1,11)
!END DO
!CLOSE (16)
!------The End
!CALL normalize (experiment,11,EXP_NUM, day_normal)

OPEN (15, FILE=INPUT)
READ (15,*) TEMP


DO I=1,SET,1
	DO J=1,EXP_NUM,1

		READ (15, 203) OUTPUT1(1,J), OUTPUT1(2,J), OUTPUT1(3,J), OUTPUT1(4,J), &
		OUTPUT1(5,J), OUTPUT1(6,J), OUTPUT1(7,J), OUTPUT1(8,J), OUTPUT1(9,J), OUTPUT1(10,J), OUTPUT1(11,J), OUTPUT1(12,J), &
		OUTPUT1(13,J), OUTPUT1(14,J), OUTPUT1(15,J), OUTPUT1(16,J), OUTPUT1(17,J), OUTPUT1(18,J),OUTPUT1(19,J), OUTPUT1(20,J), &
		OUTPUT1(21,J), OUTPUT1(22,J), OUTPUT1(23,J), OUTPUT1(24,J), OUTPUT1(25,J), OUTPUT1(26,J), OUTPUT1(27,J), OUTPUT1(28,J), &
		OUTPUT1(29,J), OUTPUT1(30,J), OUTPUT1(31,J), OUTPUT1(32,J), OUTPUT1(33,J), OUTPUT1(34,J), OUTPUT1(35,J), OUTPUT1(36,J), &
		OUTPUT1(37,J), OUTPUT1(38,J), OUTPUT1(39,J), OUTPUT1(40,J), OUTPUT1(41,J), OUTPUT1(42,J), OUTPUT1(43,J)
        203 FORMAT (F10.0,1X,17(F8.2,1X),24(F5.0,1X),F8.2)
!       203 FORMAT (F10.0,",",17(F8.2,","),24(F5.0,","),F8.2)
		OUTPUT2(1,I)=OUTPUT1(1,J)
		OUTPUT2(2,I)=OUTPUT1(2,J)
		OUTPUT2(3,I)=OUTPUT1(3,J)
		OUTPUT2(4,I)=OUTPUT1(4,J)
		OUTPUT2(5,I)=OUTPUT1(5,J)
		OUTPUT2(6,I)=OUTPUT1(6,J)
		OUTPUT2(7,I)=OUTPUT1(7,J)
		OUTPUT2(8,I)=OUTPUT1(8,J)
		OUTPUT2(9,I)=OUTPUT1(9,J)
		OUTPUT2(10,I)=OUTPUT1(10,J)
		OUTPUT2(11,I)=OUTPUT1(11,J)
		OUTPUT2(12,I)=OUTPUT1(12,J)

!For regression IEPI-IEPISIM = a+b*TMEFL (note strictly it would be nicer to regress against TMEPI)
		DATASET_EPI_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear2.txt
		DATASET_EPI_TMEFL(2,J) = OUTPUT1(35,J)-OUTPUT1(36,J)	! IEPI - IEPISIM, columns 35 & 36 of output_Bilinear2.txt
!For regression IPIFL-IPIFLSIM = a+b*TMEFL (note strictly it would be nicer to regress against TMPIFL)
		DATASET_PIFL_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear2.txt
		DATASET_PIFL_TMEFL(2,J) = OUTPUT1(37,J)-OUTPUT1(38,J)	! IPIFL - IPIFLSIM, columns 37 & 38 of output_Bilinear2.txt
!For regression IEFL-IEFLSIM = a+b*TMEFL
		DATASET_EFL_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear2.txt
		DATASET_EFL_TMEFL(2,J) = OUTPUT1(39,J) - OUTPUT1(40,J)	! IEFL-IEFLSIM in column 39 & 40 of output_Bilinear2.txt
		DATASET_EFLERROR(J) = OUTPUT1(39,J) - OUTPUT1(40,J)
!For regression IFLM-IFLMSIM = a+b*TMFLM
		DATASET_FLM_TMFLM(1,J) = OUTPUT1(17,J)					! TMFLM in column 17 of output_Bilinear2.txt
		DATASET_FLM_TMFLM(2,J) = OUTPUT1(41,J) - OUTPUT1(42,J)	! IFLM-IFLMSIM in column 41 & 42 of output_Bilinear2.txt
		DATASET_FLMERROR(J) = OUTPUT1(41,J) - OUTPUT1(42,J) 
!For regression IEM-IEMSIM = a+b*TMEM
		DATASET_EM_TMEM(1,J) = OUTPUT1(18,J)					! TMEM in column 18 of output_Bilinear2.txt
		DATASET_EM_TMEM(2,J) = (OUTPUT1(39,J)+OUTPUT1(41,J))-(OUTPUT1(40,J)+OUTPUT1(42,J))	!(IEFL+IFLM)-(IEFLSIM+IFLMSIM)
!Average CPTU at which transplanting
		DATASET_CPTUTRA(J) = OUTPUT1(43,J) 
	END DO 
!Do the regressions
	CALL SlopeCVR(DATASET_EPI_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (13,I) =SLOPE; OUTPUT2 (14,I) =RMSE
	CALL SlopeCVR(DATASET_PIFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (15,I) =SLOPE; OUTPUT2 (16,I) =RMSE
	CALL SlopeCVR(DATASET_EFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (17,I) =SLOPE; OUTPUT2 (18,I) =RMSE
	CALL AVE(DATASET_EFLERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (19,I) = AVERAGE
	CALL SlopeCVR(DATASET_FLM_TMFLM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (20,I) =SLOPE; OUTPUT2 (21,I) =RMSE
	CALL AVE(DATASET_FLMERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (22,I) = AVERAGE
	CALL SlopeCVR(DATASET_EM_TMEM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (23,I) =SLOPE; OUTPUT2 (24,I) =RMSE
	CALL AVE(DATASET_CPTUTRA, EXP_NUM, AVERAGE)
	OUTPUT2 (25,I) = AVERAGE
!Calculate development rates, rescale such that:
!0.0-0.4 = Basic Vegetative Phase
!0.4-0.65 = Photoperiod Sensitive Phase (ending at Panicle Initiation PI)
!0.65-1.0 = Post Photoperiod Sensitive Phase
!1.0-2.0 = Reproductive Phase
!	DVRJ = 0.4/SPSP
!	DVRI = (0.65-0.4)/(EPSP-SPSP)
!	DVRP = (1.-0.65)/(CPTUFL-EPSP)
!	DVRR = (2.-1.)/CPTUFLM
	IF (OUTPUT1(25,1).EQ.0..OR.OUTPUT1(6,1).EQ.0.) THEN
		DVRJ = 0.65/OUTPUT1(7,1)
		DVRI = DVRJ
	ELSE
		DVRJ = 0.4/OUTPUT1(6,1)
		DVRI = (0.65-0.4)/(OUTPUT1(7,1)-OUTPUT1(6,1))
	ENDIF
	DVRP = (1.-0.65)/(OUTPUT1(11,1)-OUTPUT1(7,1))
	DVRR = (2.-1.)/OUTPUT1(12,1)
	OUTPUT2(26,I) = DVRJ
	OUTPUT2(27,I) = DVRI
	OUTPUT2(28,I) = DVRP
	OUTPUT2(29,I) = DVRR

END DO
CLOSE (15)

output_sta="SlopeCV_bilinear2.txt"
OPEN (14, FILE=output_sta)
	WRITE (14,"(A250)") "*SET,TBD,TOD,TODNGHT,TMD,SPSP,EPSP,MOPP,PPSE,SHCKD,CPTUFL,CPTUFLM,SLOPEEPI_TMEFL,RMSE_EPI, &
	SLOPEPIFL_TMEFL,RMSE_PIFL,SLOPEEFL_TMEFL,RMSE_EFL,AVE(IEFL-IEFLSIM),SLOPEFLM_TMFLM,RMSE_FLM,AVE(IFLM-IFLMSIM), &
	SLOPEEM_TMEM,RMSE_EEM,AVE(CPTUTRA),DVRJ,DVRI,DVRP,DVRR"
	DO I=1,SET
		WRITE (14,100) (OUTPUT2(J,I), J=1,29)
		100 FORMAT (F10.0,",",11(F8.2,","), 12(F9.3, ","),F8.2,",",4(F10.7, ","))
END DO
CLOSE (14)
IF (OUTPUT1(25,1).EQ.0.) THEN
	WRITE(*,*)"You have not simulated PI. Take a good guess (e.g. 0.73*CPTUFL or IDOYFL - 20 to -30 days) and fill in the &
	Pheno_in.txt file"
ENDIF

DEALLOCATE (OUTPUT1)
DEALLOCATE (OUTPUT2)

RETURN
END SUBROUTINE



SUBROUTINE Read_Output_bilinear3()
!!! NOTICE: AVERAGE TEMPERATURES REPORTED HERE ARE WITH TM_CORR CORRECTION
! i.e. if TMEFL = 30.4 oC (average air temperature from emergence to flowering) 
! and if we assume canopy/water temperature is TM_CORR = -10.0 oC higher then
! here the output will report TMEFL = TMEFL + TM_CORR = 30.4 - 10 = 20.4 oC
REAL DATASET_EPI_TMEFL(2, EXP_NUM),DATASET_PIFL_TMEFL(2,EXP_NUM),DATASET_FLM_TMFLM(2,EXP_NUM),DATASET_EM_TMEM(2,EXP_NUM)
REAL DATASET_EFL_TMEFL(2, EXP_NUM)
REAL DATASET_CPTUTRA(EXP_NUM),DATASET_EFLERROR(EXP_NUM),DATASET_FLMERROR(EXP_NUM)

REAL day_normal (EXP_NUM), experiment (11,EXP_NUM)
REAL SLOPE, R, RMSE, AVERAGE
!REAL, ALLOCATABLE :: OUTPUT1(:,:)
CHARACTER (LEN=80) :: INPUT="output_Bilinear3.txt"

!SET = OUTPUT_NUM/EXP_NUM
ALLOCATE (OUTPUT1(43,EXP_NUM))
ALLOCATE (OUTPUT2(29,SET))

!------calcuating normalized emergence dates
!OPEN (16, FILE=pheno)
!DO I=1,EXP_NUM
!		read (16, *) (experiment(J,I) ,j=1,11)
!END DO
!CLOSE (16)
!------The End
!CALL normalize (experiment,11,EXP_NUM, day_normal)

OPEN (15, FILE=INPUT)
READ (15,*) TEMP


DO I=1,SET,1
	DO J=1,EXP_NUM,1

		READ (15, 303) OUTPUT1(1,J), OUTPUT1(2,J), OUTPUT1(3,J), OUTPUT1(4,J), &
		OUTPUT1(5,J), OUTPUT1(6,J), OUTPUT1(7,J), OUTPUT1(8,J), OUTPUT1(9,J), OUTPUT1(10,J), OUTPUT1(11,J), OUTPUT1(12,J), &
		OUTPUT1(13,J), OUTPUT1(14,J), OUTPUT1(15,J), OUTPUT1(16,J), OUTPUT1(17,J), OUTPUT1(18,J),OUTPUT1(19,J), OUTPUT1(20,J), &
		OUTPUT1(21,J), OUTPUT1(22,J), OUTPUT1(23,J), OUTPUT1(24,J), OUTPUT1(25,J), OUTPUT1(26,J), OUTPUT1(27,J), OUTPUT1(28,J), &
		OUTPUT1(29,J), OUTPUT1(30,J), OUTPUT1(31,J), OUTPUT1(32,J), OUTPUT1(33,J), OUTPUT1(34,J), OUTPUT1(35,J), OUTPUT1(36,J), &
		OUTPUT1(37,J), OUTPUT1(38,J), OUTPUT1(39,J), OUTPUT1(40,J), OUTPUT1(41,J), OUTPUT1(42,J), OUTPUT1(43,J)
!		303 FORMAT (F10.0,",",17(F8.2,","),24(F5.0,","),F8.2)
		303 FORMAT (F10.0,1X,17(F8.2,1X),24(F5.0,1X),F8.2)
		OUTPUT2(1,I)=OUTPUT1(1,J)
		OUTPUT2(2,I)=OUTPUT1(2,J)
		OUTPUT2(3,I)=OUTPUT1(3,J)
		OUTPUT2(4,I)=OUTPUT1(4,J)
		OUTPUT2(5,I)=OUTPUT1(5,J)
		OUTPUT2(6,I)=OUTPUT1(6,J)
		OUTPUT2(7,I)=OUTPUT1(7,J)
		OUTPUT2(8,I)=OUTPUT1(8,J)
		OUTPUT2(9,I)=OUTPUT1(9,J)
		OUTPUT2(10,I)=OUTPUT1(10,J)
		OUTPUT2(11,I)=OUTPUT1(11,J)
		OUTPUT2(12,I)=OUTPUT1(12,J)

!For regression IEPI-IEPISIM = a+b*TMEFL (note strictly it would be nicer to regress against TMEPI)
		DATASET_EPI_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear3.txt
		DATASET_EPI_TMEFL(2,J) = OUTPUT1(35,J)-OUTPUT1(36,J)	! IEPI - IEPISIM, columns 35 & 36 of output_Bilinear3.txt
!For regression IPIFL-IPIFLSIM = a+b*TMEFL (note strictly it would be nicer to regress against TMPIFL)
		DATASET_PIFL_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear3.txt
		DATASET_PIFL_TMEFL(2,J) = OUTPUT1(37,J)-OUTPUT1(38,J)	! IPIFL - IPIFLSIM, columns 37 & 38 of output_Bilinear3.txt
!For regression IEFL-IEFLSIM = a+b*TMEFL
		DATASET_EFL_TMEFL(1,J) = OUTPUT1(16,J)					! TMEFL in column 16 of output_Bilinear3.txt
		DATASET_EFL_TMEFL(2,J) = OUTPUT1(39,J) - OUTPUT1(40,J)	! IEFL-IEFLSIM in column 39 & 40 of output_Bilinear3.txt
		DATASET_EFLERROR(J) = OUTPUT1(39,J) - OUTPUT1(40,J)
!For regression IFLM-IFLMSIM = a+b*TMFLM
		DATASET_FLM_TMFLM(1,J) = OUTPUT1(17,J)					! TMFLM in column 17 of output_Bilinear3.txt
		DATASET_FLM_TMFLM(2,J) = OUTPUT1(41,J) - OUTPUT1(42,J)	! IFLM-IFLMSIM in column 41 & 42 of output_Bilinear3.txt
		DATASET_FLMERROR(J) = OUTPUT1(41,J) - OUTPUT1(42,J) 
!For regression IEM-IEMSIM = a+b*TMEM
		DATASET_EM_TMEM(1,J) = OUTPUT1(18,J)					! TMEM in column 18 of output_Bilinear3.txt
		DATASET_EM_TMEM(2,J) = (OUTPUT1(39,J)+OUTPUT1(41,J))-(OUTPUT1(40,J)+OUTPUT1(42,J))	!(IEFL+IFLM)-(IEFLSIM+IFLMSIM)
!Average CPTU at which transplanting
		DATASET_CPTUTRA(J) = OUTPUT1(43,J) 
	END DO 
!Do the regressions
	CALL SlopeCVR(DATASET_EPI_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (13,I) =SLOPE; OUTPUT2 (14,I) =RMSE
	CALL SlopeCVR(DATASET_PIFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (15,I) =SLOPE; OUTPUT2 (16,I) =RMSE
	CALL SlopeCVR(DATASET_EFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (17,I) =SLOPE; OUTPUT2 (18,I) =RMSE
	CALL AVE(DATASET_EFLERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (19,I) = AVERAGE
	CALL SlopeCVR(DATASET_FLM_TMFLM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (20,I) =SLOPE; OUTPUT2 (21,I) =RMSE
	CALL AVE(DATASET_FLMERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (22,I) = AVERAGE
	CALL SlopeCVR(DATASET_EM_TMEM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (23,I) =SLOPE; OUTPUT2 (24,I) =RMSE
	CALL AVE(DATASET_CPTUTRA, EXP_NUM, AVERAGE)
	OUTPUT2 (25,I) = AVERAGE
!Calculate development rates, rescale such that:
!0.0-0.4 = Basic Vegetative Phase
!0.4-0.65 = Photoperiod Sensitive Phase (ending at Panicle Initiation PI)
!0.65-1.0 = Post Photoperiod Sensitive Phase
!1.0-2.0 = Reproductive Phase
!	DVRJ = 0.4/SPSP
!	DVRI = (0.65-0.4)/(EPSP-SPSP)
!	DVRP = (1.-0.65)/(CPTUFL-EPSP)
!	DVRR = (2.-1.)/CPTUFLM
	IF (OUTPUT1(25,1).EQ.0..OR.OUTPUT1(6,1).EQ.0.) THEN
		DVRJ = 0.65/OUTPUT1(7,1)
		DVRI = DVRJ
	ELSE
		DVRJ = 0.4/OUTPUT1(6,1)
		DVRI = (0.65-0.4)/(OUTPUT1(7,1)-OUTPUT1(6,1))
	ENDIF
	DVRP = (1.-0.65)/(OUTPUT1(11,1)-OUTPUT1(7,1))
	DVRR = (2.-1.)/OUTPUT1(12,1)
	OUTPUT2(26,I) = DVRJ
	OUTPUT2(27,I) = DVRI
	OUTPUT2(28,I) = DVRP
	OUTPUT2(29,I) = DVRR

END DO

CLOSE (15)

output_sta="SlopeCV_bilinear3.txt"
OPEN (14, FILE=output_sta)
	WRITE (14,"(A250)") "*SET,TBD,TOD,TMD,TMCORR,SPSP,EPSP,MOPP,PPSE,SHCKD,CPTUFL,CPTUFLM,SLOPEEPI_TMEFL,RMSE_EPI, &
	SLOPEPIFL_TMEFL,RMSE_PIFL,SLOPEEFL_TMEFL,RMSE_EFL,AVE(IEFL-IEFLSIM),SLOPEFLM_TMFLM,RMSE_FLM,AVE(IFLM-IFLMSIM), &
	SLOPEEM_TMEM,RMSE_EEM,AVE(CPTUTRA),DVRJ,DVRI,DVRP,DVRR"
	DO I=1,SET
		WRITE (14,100) (OUTPUT2(J,I), J=1,29)
		100 FORMAT (F10.0,",",11(F8.2,","), 12(F9.3, ","),F8.2,",",4(F10.7, ","))
END DO
CLOSE (14)
IF (OUTPUT1(25,1).EQ.0.) THEN
	WRITE(*,*)"You have not simulated PI. Take a good guess (e.g. 0.73*CPTUFL or IDOYFL - 20 to -30 days) and fill in the &
	Pheno_in.txt file"
ENDIF

WRITE(*,*) "!!! NOTICE: AVERAGE TEMPERATURES REPORTED IN BILINEAR3 OUTPUT ARE WITH TM_CORR CORRECTION"
WRITE(*,*) "! i.e. if TMEFL = 30.4 oC (average air temperature from emergence to flowering)"
WRITE(*,*) "! and if we assume canopy/water temperature is TM_CORR = -10.0 oC higher then"
WRITE(*,*) "! here the output will report TMEFL = TMEFL + TM_CORR = 30.4 - 10 = 20.4 oC"


DEALLOCATE (OUTPUT1)
DEALLOCATE (OUTPUT2)

RETURN
END SUBROUTINE

SUBROUTINE Read_Output_BETA()
REAL DATASET_EPI_TMEFL(2, EXP_NUM),DATASET_PIFL_TMEFL(2,EXP_NUM),DATASET_FLM_TMFLM(2,EXP_NUM),DATASET_EM_TMEM(2,EXP_NUM)
REAL DATASET_EFL_TMEFL(2, EXP_NUM)
REAL DATASET_CPTUTRA(EXP_NUM),DATASET_EFLERROR(EXP_NUM),DATASET_FLMERROR(EXP_NUM)

REAL day_normal (EXP_NUM), experiment (11,EXP_NUM)
REAL SLOPE, R, RMSE, AVERAGE
!REAL, ALLOCATABLE :: OUTPUT1(:,:)
!SET = OUTPUT_NUM/EXP_NUM

ALLOCATE (OUTPUT1(47,EXP_NUM))
ALLOCATE (OUTPUT2(33,SET))

!------calcuating normalized emergence dates
!OPEN (16, FILE=pheno)
!DO I=1,EXP_NUM
!		read (16, *) (experiment(J,I) ,j=1,11)
!END DO
!CLOSE (16)
!------The End-------------------------------
!CALL normalize (experiment,11,EXP_NUM, day_normal)

OPEN (15, FILE=BETAOUTPUT)
READ (15,*) TEMP


DO I=1,SET,1
	DO J=1,EXP_NUM,1

		READ (15, 403) OUTPUT1(1,J), OUTPUT1(2,J), OUTPUT1(3,J), OUTPUT1(4,J), &
		OUTPUT1(5,J), OUTPUT1(6,J), OUTPUT1(7,J), OUTPUT1(8,J), OUTPUT1(9,J), OUTPUT1(10,J), OUTPUT1(11,J), OUTPUT1(12,J), &
		OUTPUT1(13,J), OUTPUT1(14,J), OUTPUT1(15,J), OUTPUT1(16,J), OUTPUT1(17,J),OUTPUT1(18,J) ,OUTPUT1(19,J) ,OUTPUT1(20,J), &
		OUTPUT1(21,J),OUTPUT1(22,J),OUTPUT1(23,J) , OUTPUT1(24,J), OUTPUT1(25,J), OUTPUT1(26,J), OUTPUT1(27,J), OUTPUT1(28,J), &
		OUTPUT1(29,J), OUTPUT1(30,J), OUTPUT1(31,J), OUTPUT1(32,J), OUTPUT1(33,J), OUTPUT1(34,J), OUTPUT1(35,J), OUTPUT1(36,J), &
		OUTPUT1(37,J), OUTPUT1(38,J), OUTPUT1(39,J), OUTPUT1(40,J), OUTPUT1(41,J), OUTPUT1(42,J), OUTPUT1(43,J), OUTPUT1(44,J), &
		OUTPUT1(45,J), OUTPUT1(46,J), OUTPUT1(47,J)
!		403 FORMAT (F10.0,",",21(F8.2,","),24(F5.0,","),F8.2)
		403 FORMAT (F10.0,1X,21(F8.2,1X),24(F5.0,1X),F8.2)

		OUTPUT2(1,I)=OUTPUT1(1,J)
		OUTPUT2(2,I)=OUTPUT1(2,J)
		OUTPUT2(3,I)=OUTPUT1(3,J)
		OUTPUT2(4,I)=OUTPUT1(4,J)
		OUTPUT2(5,I)=OUTPUT1(5,J)
		OUTPUT2(6,I)=OUTPUT1(6,J)
		OUTPUT2(7,I)=OUTPUT1(7,J)
		OUTPUT2(8,I)=OUTPUT1(8,J)
		OUTPUT2(9,I)=OUTPUT1(9,J)
		OUTPUT2(10,I)=OUTPUT1(10,J)
		OUTPUT2(11,I)=OUTPUT1(11,J)
		OUTPUT2(12,I)=OUTPUT1(12,J)
		OUTPUT2(13,I)=OUTPUT1(13,J)
		OUTPUT2(14,I)=OUTPUT1(14,J)
		OUTPUT2(15,I)=OUTPUT1(15,J)
		OUTPUT2(16,I)=OUTPUT1(16,J)

!For regression IEPI-IEPISIM = a+b*TMEFL (note strictly it would be nicer to regress against TMEPI)
		DATASET_EPI_TMEFL(1,J) = OUTPUT1(20,J)					! TMEFL in column 20 of output_Beta.txt
		DATASET_EPI_TMEFL(2,J) = OUTPUT1(39,J)-OUTPUT1(40,J)	! IEPI - IEPISIM, columns 39 & 40 of output_Beta.txt
!For regression IPIFL-IPIFLSIM = a+b*TMEFL (note strictly it would be nicer to regress against TMEPI)
		DATASET_PIFL_TMEFL(1,J) = OUTPUT1(20,J)					! TMEFL in column 20 of output_Beta.txt
		DATASET_PIFL_TMEFL(2,J) = OUTPUT1(41,J)-OUTPUT1(42,J)	! IPIFL - IPIFLSIM, columns 41 & 42 of output_Beta.txt
!For regression IEFL-IEFLSIM = a+b*TMEFL
		DATASET_EFL_TMEFL(1,J) = OUTPUT1(20,J)					! TMEFL in column 20 of output_Beta.txt
		DATASET_EFL_TMEFL(2,J) = OUTPUT1(43,J) - OUTPUT1(44,J)	! IEFL-IEFLSIM in column 43 & 44 of output_Beta.txt
		DATASET_EFLERROR(J) = OUTPUT1(43,J) - OUTPUT1(44,J)
!For regression IFLM-IFLMSIM = a+b*TMFLM
		DATASET_FLM_TMFLM(1,J) = OUTPUT1(21,J)					! TMFLM in column 21 of output_Beta.txt
		DATASET_FLM_TMFLM(2,J) = OUTPUT1(45,J) - OUTPUT1(46,J)	! IFLM-IFLMSIM in column 45 & 46 of output_Beta.txt
		DATASET_FLMERROR(J) = OUTPUT1(45,J) - OUTPUT1(46,J) 
!For regression IEM-IEMSIM = a+b*TMEM
		DATASET_EM_TMEM(1,J) = OUTPUT1(22,J)					! TMEM in column 22 of output_Beta.txt
		DATASET_EM_TMEM(2,J) = (OUTPUT1(43,J)+OUTPUT1(45,J))-(OUTPUT1(44,J)+OUTPUT1(46,J))	!(IEFL+IFLM)-(IEFLSIM+IFLMSIM)
!Average CPTU at which transplanting
		DATASET_CPTUTRA(J) = OUTPUT1(47,J) 
	END DO 
!Do the regressions
	CALL SlopeCVR(DATASET_EPI_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (17,I) =SLOPE; OUTPUT2 (18,I) =RMSE
	CALL SlopeCVR(DATASET_PIFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (19,I) =SLOPE; OUTPUT2 (20,I) =RMSE
	CALL SlopeCVR(DATASET_EFL_TMEFL,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (21,I) =SLOPE; OUTPUT2 (22,I) =RMSE
	CALL AVE(DATASET_EFLERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (23,I) = AVERAGE
	CALL SlopeCVR(DATASET_FLM_TMFLM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (24,I) =SLOPE; OUTPUT2 (25,I) =RMSE
	CALL AVE(DATASET_FLMERROR, EXP_NUM, AVERAGE)
	OUTPUT2 (26,I) = AVERAGE
	CALL SlopeCVR(DATASET_EM_TMEM,EXP_NUM,2,SLOPE, R, RMSE)
	OUTPUT2 (27,I) =SLOPE; OUTPUT2 (28,I) =RMSE
	CALL AVE(DATASET_CPTUTRA, EXP_NUM, AVERAGE)
	OUTPUT2 (29,I) = AVERAGE
!Calculate development rates, rescale such that:
!0.0-0.4 = Basic Vegetative Phase
!0.4-0.65 = Photoperiod Sensitive Phase (ending at Panicle Initiation PI)
!0.65-1.0 = Post Photoperiod Sensitive Phase
!1.0-2.0 = Reproductive Phase
!	DVRJ = 0.4/SPSP
!	DVRI = (0.65-0.4)/(EPSP-SPSP)
!	DVRP = (1.-0.65)/(CPTUFL-EPSP)
!	DVRR = (2.-1.)/CPTUFLM
	IF (OUTPUT1(29,1).EQ.0..OR.OUTPUT1(10,1).EQ.0.) THEN
		DVRJ = 0.65/OUTPUT1(11,1)
		DVRI = DVRJ
	ELSE
		DVRJ = 0.4/OUTPUT1(10,1)
		DVRI = (0.65-0.4)/(OUTPUT1(11,1)-OUTPUT1(10,1))
	ENDIF
	DVRP = (1.-0.65)/(OUTPUT1(15,1)-OUTPUT1(11,1))
	DVRR = (2.-1.)/OUTPUT1(16,1)
	OUTPUT2(30,I) = DVRJ
	OUTPUT2(31,I) = DVRI
	OUTPUT2(32,I) = DVRP
	OUTPUT2(33,I) = DVRR

END DO
CLOSE (15)

output_sta=BETASLOPECV
OPEN (14, FILE=output_sta)
	WRITE (14,"(A280)") "*SET,TBD,TMD,TOD,TODNGHT,TSEN,TSENNGHT,TSENPSP,TSENPSPNGHT,SPSP,EPSP,MOPP,PPSE,SHCKD,CPTUFL,CPTUFLM, &
	SLOPEEPI_TMEFL,RMSE_EPI,SLOPEPIFL_TMEFL,RMSE_PIFL,SLOPEEFL_TMEFL,RMSE_EFL,AVE(IEFL-IEFLSIM),SLOPEFLM_TMFLM,RMSE_FLM, &
	AVE(IFLM-IFLMSIM),SLOPEEM_TMEM,RMSE_EEM,AVE(CPTUTRA),DVRJ,DVRI,DVRP,DVRR"
	DO I=1,SET
		WRITE (14,100) (OUTPUT2(J,I), J=1,33)
		100 FORMAT (F10.0,",",15(F8.2,","), 12(F9.3, ","),F8.2,",",4(F10.7, ","))
END DO
CLOSE (14)
IF (OUTPUT1(29,1).EQ.0.) THEN
	WRITE(*,*)"You have not simulated PI. Take a good guess (e.g. 0.73*CPTUFL or IDOYFL - 20 to -30 days) and fill in the &
	Pheno_in.txt file"
ENDIF


DEALLOCATE (OUTPUT1)
DEALLOCATE (OUTPUT2)

RETURN
END SUBROUTINE




!-----SUBROUTINE TO CALCULATE SLOPE, CV, R, RMSE
SUBROUTINE SlopeCVR(X,M,N,SLOPE, R, RMSE)
!DIMENSION X(N,M),Y(N),R(N-1),SLOPE(N-1),INTERCEPT(N-1),YY(N),A(N-1),B(N)
DIMENSION X(N,M),Y(N),YY(N),B(N)
!DIMENSION SE(N-1)
REAL X,Y,R,SLOPE,INTERCEPT,SE,YY,A,B, C, CV, RMSE
  DO I=1,N
   YY(I)=0.0
      DO J=1,M
    YY(I)=YY(I)+X(I,J)
      ENDDO
    Y(I)=YY(I)/M   !Y(1)is average for X; Y(2) is average for Y
  ENDDO

!  DO I=1,N-1
!   A(I)=0.0
!      DO J=1,M
!         A(I)=A(I)+(X(I,J)-Y(I))*(X(N,J)-Y(N)) !LXY
!      ENDDO  
!  ENDDO
A=0.0
DO J=1,M
   A=A+(X(1,J)-Y(1))*(X(N,J)-Y(N)) !LXY
ENDDO  
DO I=1,N
  B(I)=0.0
      DO J=1,M
  B(I)=B(I)+(X(I,J)-Y(I))**2 !LXX,LYY
      ENDDO
ENDDO

DO I=N,N
	C=0.0
	D=0.0
	DO J=1,M
		C=C+(X(I,J)-Y(I))**2  !LYY
		D=D+X(I,J) 
	END DO
		D=D/M                 !AVERAGE OF Y
END DO

!DO I=1,N-1
!	R(I)=A(I)/SQRT(B(I)*B(N))
!	SLOPE(I)=A(I)/B(I)
!	INTERCEPT(I)=Y(N)-SLOPE(I)*Y(I)
!ENDDO
R=A/SQRT(B(1)*B(N))
SLOPE=A/B(1)
INTERCEPT=Y(1)-SLOPE*Y(1)

!CV   =SQRT(C/(M-1))/D*100
RMSE =SQRT(C/M)

RETURN
END SUBROUTINE

!-----SUBROUTINE TO CALCULATE AVERAGE
SUBROUTINE AVE(X,M,AVE_SUB)
INTEGER M
REAL X(M)
REAL AVE_SUB


REAL SUM_SUB

SUM_SUB=0.0

DO I=1,M
	SUM_SUB=SUM_SUB+X(I)
END DO

AVE_SUB=SUM_SUB/FLOAT(M)

RETURN
END SUBROUTINE



END MODULE
